language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t timmelcherson/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true timmelcherson/udemy-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-773901293218"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY